[package]
name = "nali-rs"
version = "0.1.0"
authors = ["KasumigaokaUtaha <blacklotussaki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipdb-parser = { path = "../ipdb-parser" }
clap = "2.33.3"